SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `CSE_ADMIN_SYSTEM` ;
CREATE SCHEMA IF NOT EXISTS `CSE_ADMIN_SYSTEM` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `CSE_ADMIN_SYSTEM` ;

-- -----------------------------------------------------
-- Table `CSE_ADMIN_SYSTEM`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CSE_ADMIN_SYSTEM`.`USUARIO` ;

CREATE  TABLE IF NOT EXISTS `CSE_ADMIN_SYSTEM`.`USUARIO` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT ,
  `NOMBRE` VARCHAR(50) NOT NULL ,
  `APELLIDO` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`ID_USUARIO`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSE_ADMIN_SYSTEM`.`Perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CSE_ADMIN_SYSTEM`.`Perfil` ;

CREATE  TABLE IF NOT EXISTS `CSE_ADMIN_SYSTEM`.`Perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT ,
  `NOMBRE_PERFIL` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`idPerfil`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSE_ADMIN_SYSTEM`.`LOGIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CSE_ADMIN_SYSTEM`.`LOGIN` ;

CREATE  TABLE IF NOT EXISTS `CSE_ADMIN_SYSTEM`.`LOGIN` (
  `ID_LOGIN` INT NOT NULL AUTO_INCREMENT ,
  `USUARIO` VARCHAR(45) NOT NULL ,
  `PASSWORD` VARCHAR(45) NOT NULL ,
  `USUARIO_ID_USUARIO` INT NOT NULL ,
  `Perfil_idPerfil` INT NOT NULL ,
  PRIMARY KEY (`ID_LOGIN`) ,
  INDEX `fk_LOGIN_USUARIO_idx` (`USUARIO_ID_USUARIO` ASC) ,
  INDEX `fk_LOGIN_Perfil1_idx` (`Perfil_idPerfil` ASC) ,
  CONSTRAINT `fk_LOGIN_USUARIO`
    FOREIGN KEY (`USUARIO_ID_USUARIO` )
    REFERENCES `CSE_ADMIN_SYSTEM`.`USUARIO` (`ID_USUARIO` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LOGIN_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil` )
    REFERENCES `CSE_ADMIN_SYSTEM`.`Perfil` (`idPerfil` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSE_ADMIN_SYSTEM`.`MENU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CSE_ADMIN_SYSTEM`.`MENU` ;

CREATE  TABLE IF NOT EXISTS `CSE_ADMIN_SYSTEM`.`MENU` (
  `idMenu` INT NOT NULL AUTO_INCREMENT ,
  `NOMBRE_MENU` VARCHAR(45) NOT NULL ,
  `ACCION_MENU` VARCHAR(45) NOT NULL ,
  `Perfil_idPerfil` INT NOT NULL ,
  PRIMARY KEY (`idMenu`) ,
  INDEX `fk_MENU_Perfil1_idx` (`Perfil_idPerfil` ASC) ,
  CONSTRAINT `fk_MENU_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil` )
    REFERENCES `CSE_ADMIN_SYSTEM`.`Perfil` (`idPerfil` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `CSE_ADMIN_SYSTEM` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
